### ISSUE TITLE
BigMapAbstraction.get method no longer catches 404 errors

### ISSUE THREAD

**Issue by sirrocco** [ecadlabs/taquito#2187] opened 2022-12-02 08:42 UTC
**Description**
I assume the issue appeared since the introduction of `vespaiach/axios-fetch-adapter`.

In the `BigMapAbstraction` class, the method `get` tries to handle `404` responses.
However, 404 responses in the browser no longer trigger an exception of type `HttpResponseError` but `HttpRequestFailed`.

As a result, the exception is thrown instead of returning `undefined`.

**Steps To Reproduce**
1. Be in a Browser environment
2. Try to load a non-existent key from a bigmap.

**Expected behavior**
The function should return `undefined`

**Actual behavior**
The function throws an exception

**Desktop (please complete the following information):**
 - any browser environment

Thank you.

**Comment by dsawali** [comment] 2022-12-29 17:36
Thanks for the issue @sirrocco. I got a chance to look into this regression and it goes a bit deeper than expected.

Starting from version 14.1.0, we introduced a dependency that allows for fetch based http request in Axios called `vespaiach/axios-fetch-adapter` as you mentioned above.

It introduced an unexpected behaviour where the error response wasn't being passed on to the error object in our codebase. Our code relies on the error response to make a decision on what to throw. In your case, a 404 using the fetch adapter (browser, service worker environments will use the fetch adapter instead of Axios) will result in an `HttpRequestFailed`. That is indeed _not_ the expected behaviour.

I think the problem relies with the fetch adapter and how it passes on errors, so we're going to fork the library and maintain our own instance for now, just until Axios provides official support for fetch based http requests.

On that note, we're looking into putting in the fix for this in version 15.1.0.

**Comment by dsawali** [comment] 2022-12-29 23:37
Hello @sirrocco, we currently have a preview build available for you to test out. You can install it by doing:
```
npm i @taquito/taquito@15.0.1-7c75c49-- --registry https://npm.preview.tezostaquito.io/
```
Do keep in mind that this isn't an official release. We are planning to do a 15.1.0 release hopefully sometime early January. But you can use this preview build to play around and see if the issue is resolved. Please let us know if you have any concerns.

**Comment by dsawali** [comment] 2023-01-03 17:41
cool, thank you for updating us @sirrocco. We will update you and the community once we have 15.1.0 ready.

**Closed** 2023-01-04 17:43 UTC
Labels: bug
