### ISSUE TITLE
DOC: How to add support for a new Protocol to Taquito

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#479] opened 2020-11-09 19:51 UTC
As a potential contributor or core protocol engineer, I would like to know how I can add support for a new protocol to Taquito 
See an initial notion page: https://www.notion.so/ecad/Adding-a-new-protocol-07496f004819476599a08b76e8464c14

**Comment by michaelkernaghan** [comment] 2023-04-17 13:36
this is a duplicate of #500

**Closed by michaelkernaghan** 2023-04-17 13:36 UTC
Labels: documentation
