### ISSUE TITLE
Add integration tests for Permit contracts (TZIP-17)

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#661] opened 2021-03-02 00:12 UTC
**The goal of this ticket is to confirm that Taquito users can manipulate permit contracts using the new data packing feature (https://github.com/ecadlabs/taquito/issues/613).**

Permit can be created and consumed via Permit entry point that requires a signed hashed parameter (pack bytes first and then blake2b that is already supported by Taquito). 

See more details here:
- Original spec: https://gitlab.com/tzip/tzip/-/blob/master/proposals/tzip-17/tzip-17.md
- More information on TZIP-17 with references and an overview here:
https://www.notion.so/ecad/Taquito-EPIC-TZIP-17-Permit-e9439f9dc7ea41c790ff50eee6ad9928
- Examples for Taquito in Michel Klein's tests here: [https://github.com/tqtezos/lorentz-contract-permit/blob/add-admin-42/README_SET.md](https://github.com/tqtezos/lorentz-contract-permit/blob/add-admin-42/README_SET.md)

OUT OF SCOPE:
Any high-level abstractions or validations for compliance with TZIP-17.

**Acceptance criteria:*
- The following is covered in integration tests:
   - permit can be submitted and used, expiration can be set
   - required off-chain views can be executed
   - Storage tables are accessible: permits, user_expiries, permit_expiries.
   - Failure scenarios: Expiry, not enough funds, etc. 
- Suggested high-level scenario (please break it down where it makes sense):
   - Originate permit smart contract (see examples for Taquito in Michel Klein's tests)
   - Retrieve the contract: metadata, storage, entry points, and off-chain views
   - Contract owner adds permit 1 from the contract owner through the contract using Permit entrypoint
   - A new tz account adds permit 2 and 3(2 permits in a batch) through the contract using Permit entrypoint
   - Update expiry date using SetExpiry on permit #3 to expire before the end of the test.
   - Execute GetDefaultExpiry and GetCounter off-chain-views 
   - Execute each permit from another new tz account: 
      - Permit 3 should be expired and have an error
   - Add more variations around Michelson code to be executed where it makes sense:
      - transactions, any batched operations

**Comment by michaelkernaghan** [comment] 2021-06-21 20:54
This is a duplicate of the issue #893  and will be closed when that is merged.

**Comment by Innkst** [comment] 2021-07-02 20:06
see #953 for the usage of the permit

**Comment by michaelkernaghan** [comment] 2021-07-07 13:56
This can be closed the Pr was cancelled. Another PR was made, which included #953 as well.

**Closed by michaelkernaghan** 2021-07-07 13:56 UTC
Labels: testing🧪
