### ISSUE TITLE
Breaking changes Gas Limits

### ISSUE THREAD

**Issue by zainen** [ecadlabs/taquito#2406] opened 2023-03-27 21:13 UTC
**Description**
Mondaynet march 27 2023 introduced gas limit changes that break estimations for our estimate provider
tests break inconsistnely as gas costs vary from tz1/2/3/4 

more information can be found at this link

https://tezos.gitlab.io/protocols/alpha.html#gas-improvements

**Steps To Reproduce**
run integration tests against mondaynet. various tests will fail for gas exhaustion

**Expected behavior**
all mondaynet tests should pass

**Comment by Innkst** [comment] 2023-04-24 20:26
duplicate of #2447

**Closed by Innkst** 2023-04-24 20:26 UTC
Labels: breaking change, testing🧪, N protocol
