### ISSUE TITLE
Re-export types from @airgap/beacon-sdk

### ISSUE THREAD

**Issue by shekhar-shubhendu** [ecadlabs/taquito#808] opened 2021-04-24 11:11 UTC
**Is your feature request related to a problem and use case? Please describe.**
To use types from `@airgap/beacon-sdk` we have to install `@airgap/beacon-sdk` again although an equivalent version exists with taquito

**Describe the solution you'd like**
Re-export types provided by `@airgap/beacon-sdk`

**Describe alternatives you've considered**
The only alternative apart from installing `@airgap/beacon-sdk` is to re-create them in the application/library

**Additional context**
I'm not sure if this is same as #778 if so then please close this one (and let me know so I can track it there)

**Comment by roxaneletourneau** [comment] 2021-04-29 22:09
Hi, are you referring to the Network enum? Are there other specific types you would like us to export?

**Comment by shekhar-shubhendu** [comment] 2021-04-30 09:23
@roxaneletourneau I think for now these will work
https://github.com/ecadlabs/taquito/blob/master/packages/taquito-beacon-wallet/src/taquito-beacon-wallet.ts#L6

**Comment by michaelkernaghan** [comment] 2022-01-24 20:45
Closed as duplicate of Export BeaconWallet types/enums #778

**Closed by michaelkernaghan** 2022-01-24 20:45 UTC
Labels: beacon-sdk
