### ISSUE TITLE
Use an object as a parameter for entrypoints instead of a series of parameters

### ISSUE THREAD

**Issue by claudebarde** [ecadlabs/taquito#534] opened 2020-12-03 15:35 UTC
The current behaviour is the following: if a contract entrypoint accepts a nested pair like `(pair (%owner address) (pair (%amount tez) (pair (%name string) (%last_update timestamp))))`, the parameters must be sent as separate values like: `contract.methods.entrypoint(address, tez, name, last_update).send()`. This becomes confusing if the parameters are complex or numerous.

It will be a lot more readable and easier to use an object as the parameter like `contract.methods.entrypoint({ address, tez, name, last_update }).send()`. 

This behaviour already exists for pairs in lists (a transaction sent to an entrypoint accepting a list of the previous pair would be created with Taquito with `contract.methods.entrypoint([{ address, tez, name, last_update }]).send()`).

**Comment by jevonearth** [comment] 2020-12-03 18:53
Related to #418

**Comment by roxaneletourneau** [comment] 2021-11-22 21:53
duplicate of: https://github.com/ecadlabs/taquito/issues/915
implemented in : https://github.com/ecadlabs/taquito/pull/1029

**Closed by roxaneletourneau** 2021-11-22 21:53 UTC
