### ISSUE TITLE
SPIKE: Sapling abstractions

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#450] opened 2020-10-22 15:40 UTC
This is a placeholder to gather information for future sapling support in Taquito. Should readers have questions or suggestions, please feel free to use the comments :arrow_down: 

- Tezos documentation for Sapling: https://gitlab.com/metastatedev/tezos/-/blob/sapling-integration/docs/developer/sapling.rst
- MR for adding sapling to Tezos: https://gitlab.com/metastatedev/tezos/-/merge_requests/232
- AirGap project focusing on compiling the `librustzcash` rust reference implementation to wasm: https://github.com/airgap-it/airgap-sapling-wasm/tree/develop

We have already added new sapling RPCs and required types, integration tests are added for those items too.

Acceptance criteria:
- Research:
   - How do sapling keys relate to tezos keys? Should we or should we not use the same bip-39 keys for a Tezos address for the Sapling keys? Are there recommendations?
   - Figure out how BIP-39 and ZIP-32 diverge. Can we support both without sowing confusion in the ecosystem?
   - Play with the contracts from the tezos repo here:
   - Check if multi-asset contract is ready and published to mainnet
   - TBD if we need to research more areas
- Document use case workflow on how shielded pools can be used by users, happy path and failure
- Identify high-level abstractions that can help manipulate data to optimize user interactions with Taquito to use sapling transactions.

**Comment by michaelkernaghan** [comment] 2022-02-02 22:36
dupe of #586

**Comment by roxaneletourneau** [comment] 2022-02-02 22:47
Re-opening this issue, Areas to research have not been covered.

**Closed** 2022-04-26 16:13 UTC
