### ISSUE TITLE
Document how to capture failwith errors

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#257] opened 2020-02-12 20:23 UTC
Doc how Taquito users can smart contract errors surfaced by the `FAILWITH` michelson instruction.

```ts
catch (ex) {
   if (ex instanceof TezosOperationError) {
       if(ex.message === "E_TOMANYBLURBS") {
          //handle error
        }
    }
}
```

**Comment by DalyIng** [comment] 2020-02-20 11:05
Hi, this functionnality already exists? If yes, can you please give us a small example, I need it in hurry.
Thanks in advance.

**Comment by jevonearth** [comment] 2020-02-20 11:52
Hi @DalyIng 

Yes, Taquito supports this in the latest version. This relies on the Michelson [FAILWITH](https://michelson.nomadic-labs.com/#instr-FAILWITH) instruction.

If you are using Ligo for example, a contract that has a function such as the following;

```
function fail_if_not_admin(const admins: set(address)): unit is
  block {
    if (not(set_mem(sender, admins))) then
      failwith("You don't have this privilege.")
    else skip
  } with unit
```

And the `failwith` gets executed during an operation, you can catch that error in Taquito as follows;

```
catch (ex) {
   if (ex instanceof TezosOperationError) {
       if(ex.message === "You don't have this privilege.") {
          //handle error
        }
    }
}
```

I recommend you define error codes when using `failwith`, instead of human-readable strings.

We have a demo app that implements this here: https://github.com/ecadlabs/proposal-vote/blob/bf738d68361711a081f399928cbec7edb250e17f/src/components/voter-panel.tsx#L99 for your reference.

If this covers your question, please feel free to close this issue. :)

**Comment by DalyIng** [comment] 2020-02-20 12:49
Hi @jevonearth ,
Great answer, thank you! I'll close the issue.

**Comment by jevonearth** [comment] 2020-02-20 12:54
Ha, yes, I forgot this issue is for me and by me to document this feature :laughing: 
Thank you @DalyIng

**Comment by chiptus** [comment] 2020-08-10 11:39
https://gitlab.com/tzip/tzip/-/blob/master/proposals/tzip-7/tzip-7.md

what about failwith that returns with a tuple? like NotEnoughAllowance?

**Comment by chiptus** [comment] 2020-08-10 11:59
and is this working with beacon? because I get a popup of "ParametersInvalid" and error that is not really parsable:
![image](https://user-images.githubusercontent.com/1381655/89780403-0f447a00-db1a-11ea-8a64-f0b9d1c716c8.png)

**Comment by claudebarde** [comment] 2020-08-11 15:38
I've just run some tests with the following code:
- a simple Michelson contract that always fails
```
parameter unit ;
storage unit ;
code {
    ## PUSH string "failed!"
    ## PUSH int 88 ;
    ## UNIT ;
    ## PUSH (pair string string) (Pair "hello" "world");
    FAILWITH ;
}
```

- a Truffle test file to run the tests quickly (I bypassed Truffle implementation to use Taquito directly)
```
const Test = artifacts.require("Test");
const { Tezos } = require("@taquito/taquito");
const { InMemorySigner } = require("@taquito/signer");
const { alice } = require("../scripts/sandbox/accounts");

contract("Contract fails with pair", () => {
  it("should fail", async () => {
    const contract = await Test.deployed();
    Tezos.setProvider({
      rpc: "http://localhost:8732",
      signer: await InMemorySigner.fromSecretKey(alice.sk)
    });
    const instance = await Tezos.contract.at(contract.address);

    try {
      const op = await instance.methods.main([["unit"]]).send();
      await op.confirmation();
    } catch (error) {
      console.error(error);
    }
  });
});
```

Every value that was not a string on the stack when the contract fails produces the same error: `(temporary) proto.006-PsCARTHA.michelson_v1.script_rejected`. You can find a description of the error [here](https://tezos.gitlab.io/api/errors.html#ref102descr).
I don't think it is possible to return anything but a string from a Michelson contract, although this is not documented as far as I know.

**Comment by chiptus** [comment] 2020-08-11 16:15
is it a limitation of michelson or taquito? TZIP-7 specifically says that NotEnoughAllowance should return with a tuple of how much is allowed and how much was requested

**Comment by chiptus** [comment] 2020-08-11 16:17
My error is thrown when I fail with a string, so I guess it's a bug with beacon?

**Comment by claudebarde** [comment] 2020-08-11 16:24
I think it's a limitation of Michelson although I want to check that first and I will let you know.
TZIP-7 does specify it but in a real-life example, returning a pair doesn't work :P I also have never seen a contract returning anything else but an error-code as a string after `FAILWITH`. I will get more details about that!

**Comment by chiptus** [comment] 2020-08-12 14:34
Archetype now support `failwith` with any type argument, can it be the case that taquito just doesn't know how to parse it?
https://github.com/edukera/archetype-lang/releases/tag/1.1.1

**Comment by claudebarde** [comment] 2020-08-12 15:53
This is not what the release message says (there is nothing about `failwith`), Archetype has instructions called [`fail` or `failif`](https://docs.archetype-lang.org/archetype-language/action#failing) and them returning a pair doesn't mean Michelson's `FAILWITH` can return a pair too.
I am still investigating it but so far it looks like the error message returned by Taquito is sent from the Tezos node that ran the contract, I will let you know when I find more about it...

**Comment by claudebarde** [comment] 2020-08-12 16:20
I deployed [this contract](https://better-call.dev/carthagenet/KT1VYUxhLoSvouozCaDGL1XcswnagNfwr3yi/code) on Carthagenet that fails with a pair if you want to make some tests yourself. So far, I can see that Taquito and Conseil show `(temporary) proto.006-PsCARTHA.michelson_v1.script_rejected` as a result of the transaction but a transaction sent from the `tezos-client` command line indicates `script reached FAILWITH instruction with (Pair "hello" "world")` so some further investigations are necessary :)

**Comment by chiptus** [comment] 2020-08-12 17:24
> This is not what the release message says (there is nothing about `failwith`), Archetype has instructions called [`fail` or `failif`](https://docs.archetype-lang.org/archetype-language/action#failing) and them returning a pair doesn't mean Michelson's `FAILWITH` can return a pair too.
> I am still investigating it but so far it looks like the error message returned by Taquito is sent from the Tezos node that ran the contract, I will let you know when I find more about it...

actually, they implemented it after I asked how to implement FA1.2 if we can't failwith with different types. when transpiling their [FA1.2 code](https://docs.archetype-lang.org/contract-library/tokens/fa-1.2) you can see it creates a function `fail_tuple_string_tuple_nat_nat` that does exactly what I was asking about. 

Checking your contract on BakingBad, when you interact with using beacon, you'll an error popup that shows exactly that:
![image](https://user-images.githubusercontent.com/1381655/90046733-8a07c380-dcd9-11ea-955e-2452f0784f2f.png)

So the right parameters return, the problem is that the caller of the contract doesn't get this error, he only gets:
![image](https://user-images.githubusercontent.com/1381655/90046898-c509f700-dcd9-11ea-9479-422a607a2705.png)

**Comment by claudebarde** [comment] 2020-08-12 17:34
Thank you for the screenshot with the JSON value, that's really helpful.
Let me check that with the Taquito team :)

**Comment by chiptus** [comment] 2020-08-12 17:35
Should have noticed it a while ago :D

**Comment by claudebarde** [comment] 2021-02-23 14:15
@jevonearth This feature has been implemented by the beacon-sdk and the major wallets and tested by myself. I am not sure if you think it deserves to be documented, the actual value is buried a bit in the error message but easy to access.

**Closed** 2022-04-20 16:13 UTC
Labels: documentation
